"""Add default_credential_id to servers

Revision ID: 19e51cd559f6
Revises: 
Create Date: 2026-01-12 13:24:40.357194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19e51cd559f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_site_availability_site_time'), table_name='site_availability')
    op.drop_index(op.f('idx_site_availability_time'), table_name='site_availability')
    op.drop_index(op.f('site_availability_time_idx'), table_name='site_availability')
    op.drop_table('site_availability')
    op.drop_index(op.f('idx_server_metrics_server_time'), table_name='server_metrics')
    op.drop_index(op.f('idx_server_metrics_time'), table_name='server_metrics')
    op.drop_index(op.f('server_metrics_time_idx'), table_name='server_metrics')
    op.drop_table('server_metrics')
    op.drop_index(op.f('database_metrics_time_idx'), table_name='database_metrics')
    op.drop_index(op.f('idx_database_metrics_db_time'), table_name='database_metrics')
    op.drop_index(op.f('idx_database_metrics_time'), table_name='database_metrics')
    op.drop_table('database_metrics')
    op.drop_index(op.f('device_metrics_time_idx'), table_name='device_metrics')
    op.drop_index(op.f('idx_device_metrics_device_time'), table_name='device_metrics')
    op.drop_index(op.f('idx_device_metrics_time'), table_name='device_metrics')
    op.drop_table('device_metrics')
    op.alter_column('business_sites', 'check_interval',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='检查间隔（秒），默认300秒（5分钟）',
               existing_nullable=True,
               existing_server_default=sa.text('300'))
    op.alter_column('business_sites', 'check_timeout',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='检查超时时间（秒），默认10秒',
               existing_nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('business_sites', 'check_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='其他检查配置（JSON格式，如请求头、请求方法等）',
               existing_nullable=True)
    op.alter_column('business_sites', 'is_maintenance',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否处于维护模式',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('business_sites', 'maintenance_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='维护开始时间',
               existing_nullable=True)
    op.alter_column('business_sites', 'maintenance_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='维护结束时间',
               existing_nullable=True)
    op.alter_column('business_sites', 'maintenance_note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='维护说明',
               existing_nullable=True)
    op.alter_column('business_sites', 'health_score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='健康度评分（0-100）',
               existing_nullable=True)
    op.alter_column('business_sites', 'health_score_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='健康度评分更新时间',
               existing_nullable=True)
    op.add_column('servers', sa.Column('default_credential_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'servers', 'credentials', ['default_credential_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'servers', type_='foreignkey')
    op.drop_column('servers', 'default_credential_id')
    op.alter_column('business_sites', 'health_score_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='健康度评分更新时间',
               existing_nullable=True)
    op.alter_column('business_sites', 'health_score',
               existing_type=sa.INTEGER(),
               comment='健康度评分（0-100）',
               existing_nullable=True)
    op.alter_column('business_sites', 'maintenance_note',
               existing_type=sa.TEXT(),
               comment='维护说明',
               existing_nullable=True)
    op.alter_column('business_sites', 'maintenance_end',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='维护结束时间',
               existing_nullable=True)
    op.alter_column('business_sites', 'maintenance_start',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='维护开始时间',
               existing_nullable=True)
    op.alter_column('business_sites', 'is_maintenance',
               existing_type=sa.BOOLEAN(),
               comment='是否处于维护模式',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('business_sites', 'check_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='其他检查配置（JSON格式，如请求头、请求方法等）',
               existing_nullable=True)
    op.alter_column('business_sites', 'check_timeout',
               existing_type=sa.INTEGER(),
               comment='检查超时时间（秒），默认10秒',
               existing_nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('business_sites', 'check_interval',
               existing_type=sa.INTEGER(),
               comment='检查间隔（秒），默认300秒（5分钟）',
               existing_nullable=True,
               existing_server_default=sa.text('300'))
    op.create_table('device_metrics',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interface_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('interface_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('bytes_in', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('bytes_out', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('packets_in', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('packets_out', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('errors_in', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('errors_out', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('cpu_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('temperature', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('idx_device_metrics_time'), 'device_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_device_metrics_device_time'), 'device_metrics', ['device_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('device_metrics_time_idx'), 'device_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_table('database_metrics',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('database_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connections_current', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('connections_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('queries_per_second', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('slow_queries', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cache_hit_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('database_size', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('table_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lock_wait_count', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('idx_database_metrics_time'), 'database_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_database_metrics_db_time'), 'database_metrics', ['database_id', sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('database_metrics_time_idx'), 'database_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_table('server_metrics',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('server_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cpu_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_used', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('memory_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('memory_cached', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('memory_swap', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('disk_used', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('disk_total', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('disk_io_read', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('disk_io_write', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('network_in', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('network_out', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('load_avg_1m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('load_avg_5m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('load_avg_15m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('server_metrics_time_idx'), 'server_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_server_metrics_time'), 'server_metrics', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_server_metrics_server_time'), 'server_metrics', ['server_id', sa.literal_column('time DESC')], unique=False)
    op.create_table('site_availability',
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('site_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dns_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ssl_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f('site_availability_time_idx'), 'site_availability', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_site_availability_time'), 'site_availability', [sa.literal_column('time DESC')], unique=False)
    op.create_index(op.f('idx_site_availability_site_time'), 'site_availability', ['site_id', sa.literal_column('time DESC')], unique=False)
    # ### end Alembic commands ###

